version: '3'

services:
  mongodb:
    image: mongo

    environment:
      - MONGO_INITDB_ROOT_USERNAME=magoo 
      - MONGO_INITDB_ROOT_PASSWORD=t1y2p3e4
    ports:
      - 27017-27019:27017-27019
    volumes:
      - DBTestStorage:/data
    networks:
      - muse-net

  backend:
<<<<<<< HEAD
    image: gohttp
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - CONN_STRING="mongodb://magoo:t1y2p3e4@localhost:27017/test?authSource=admin"
=======
    image: newhttp
    build:
      context: .
      dockerfile: Dockerfile-2.yml
>>>>>>> master
    ports:
      - 8090:8090
    networks:
      - muse-net
<<<<<<< HEAD
  

=======
    
>>>>>>> master


volumes:
  DBTestStorage:
networks:
  muse-net: