version: '3'

services:
  mongodb:
    image: mongo:latest

    environment:
      - MONGO_INITDB_ROOT_USERNAME=magoo
      - MONGO_INITDB_ROOT_PASSWORD=t1y2p3e4
    ports:
      - 27017-27019:27017-27019
    volumes:
      - DBTestStorage:/data
    networks:
      - muse-net

  backend:
    image: gohttp:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - CONN_STRING=mongodb://magoo:t1y2p3e4@mongodb:27017/test?authSource=admin
    ports:
      - 8090:8090
    networks:
      - muse-net

  frontend:
    image: musefront
    build:
      context: ./client
      dockerfile: Dockerfile-2
    ports:
      - 3000:3000
    networks:
      - muse-net
    volumes:
      - Frontend:/frontend

volumes:
  DBTestStorage:
  Frontend:
networks:
  muse-net:
