version: '3'

services:
  mongodb:
    image: mongo

    environment:
      - MONGO_INITDB_ROOT_USERNAME=magoo 
      - MONGO_INITDB_ROOT_PASSWORD=t1y2p3e4
    ports:
      - 27017-27019:27017-27019
    volumes:
      - DBTestStorage:/data
    networks:
      - muse-net

  backend:
    image: newhttp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    networks:
      - muse-net
    


volumes:
  DBTestStorage:
networks:
  muse-net: